import { useState } from "react";
import { Link, useNavigate } from "react-router-dom";

const NAVY = "#0B1F3A";
const GOLD = "#C9A227";
const TEAL = "#0D9488";

const ASSET = "USDT TRC20";
// Your Tron Address
const ADDRESS = "TAEJkCFJmYCXHkSCWHZpbStPzBsEkRSPij"; 
const AMOUNT = "100";

export default function Payment() {
  const navigate = useNavigate();
  const [copied, setCopied] = useState(false);
  const [txHash, setTxHash] = useState("");
  const [verifying, setVerifying] = useState(false);
  const [error, setError] = useState("");

  function copyAddr() {
    navigator.clipboard.writeText(ADDRESS);
    setCopied(true);
    setTimeout(() => setCopied(false), 1500);
  }

  async function handlePaid(e: React.FormEvent) {
    e.preventDefault();
    setError("");

    if (!txHash.trim()) {
      setError("Please paste your Transaction Hash (TxID).");
      return;
    }

    setVerifying(true);

    try {
      // 1. Fetch transaction data from TronGrid API
      const response = await fetch(
        `https://api.trongrid.io/v1/transactions/${txHash}`
      );
      
      const data = await response.json();

      if (!data || data.code === "FAILED") {
        throw new Error("Transaction not found or failed.");
      }

      // 2. Check if the transaction is confirmed
      // Note: 'confirmed' means it's on the blockchain. 
      // For USDT, you usually want to check the contract result or wait for finality.
      // For this example, we check if it exists and succeeded.
      
      // 3. Verify the amount and recipient
      let verified = false;
      
      // Check contract result for USDT transfers
      if (data.contract_result && data.contract_result === "01") {
        // Look through contract data for the transfer
        // This is a simplified check. USDT on Tron is a smart contract interaction.
        // We need to check the 'data' field or use a more specific API endpoint for contract calls.
        
        // Better approach for USDT: Check if the transaction involves the USDT contract address
        // and if the 'data' field indicates a transfer > 0.
        
        // For simplicity in client-side, we check if the transaction succeeded 
        // and optionally cross-reference with a block explorer API if needed.
        // However, the most robust client-side check is verifying the receipt.
        
        // Let's check the internal transactions (transfers) generated by this tx
        const internalsResponse = await fetch(
          `https://api.trongrid.io/v1/transactions/${txHash}/internal_transactions`
        );
        const internals = await internalsResponse.json();
        
        const internalTx = internals?.transactions?.[0];
        
        if (internalTx) {
          const receiver = internalTx.contract[0]?.parameter?.value?.to_address || "";
          const amountInSun = internalTx.contract[0]?.parameter?.value?.amount || "0";
          const amountInUsdt = parseInt(amountInSun) / 1000000; // 1 USDT = 1,000,000 SUN

          if (receiver === ADDRESS && amountInUsdt >= parseFloat(AMOUNT)) {
            verified = true;
          }
        }
      }

      if (!verified) {
        throw new Error("Transaction verified, but amount or recipient does not match.");
      }

      // Success
      localStorage.setItem("paid", "1");
      localStorage.setItem("pay_method", "crypto");
      navigate("/finalize");

    } catch (err: any) {
      setError(err.message || "Could not verify payment. Check your TxID and try again.");
    } finally {
      setVerifying(false);
    }
  }

  return (
    <div className="min-h-screen flex flex-col items-center justify-center px-4 py-16" style={{ backgroundColor: "#F7F8FA" }}>
      <div className="w-full max-w-[480px]">
        <div className="text-center mb-10">
          <div
            className="inline-flex items-center gap-2 px-3 py-1.5 rounded-full text-xs font-semibold tracking-widest uppercase mb-6"
            style={{ backgroundColor: `${TEAL}15`, color: TEAL, border: `1px solid ${TEAL}30` }}
          >
            Step 2 of 4
          </div>
          <h1 className="text-3xl font-black mb-2" style={{ color: NAVY }}>Submit Payment</h1>
          <p className="text-sm" style={{ color: "#6B7280" }}>
            Transparent pricing. $100 crypto. No upsells.
          </p>
        </div>

        <div className="bg-white rounded-[12px] p-6 mb-6 flex items-center justify-between" style={{ border: "1px solid #D0D5DD" }}>
          <div>
            <p className="text-sm font-semibold" style={{ color: NAVY }}>Wyoming LLC Formation</p>
            <p className="text-xs mt-0.5" style={{ color: "#9CA3AF" }}>One-time · {ASSET}</p>
          </div>
          <p className="text-2xl font-black" style={{ color: NAVY }}>${AMOUNT}</p>
        </div>

        <div className="bg-white rounded-[12px] p-8" style={{ border: "1px solid #D0D5DD", boxShadow: "0 4px 24px rgba(11,31,58,0.06)" }}>
          <form onSubmit={handlePaid} className="space-y-4">
            <p className="text-sm font-semibold" style={{ color: NAVY }}>Send exactly ${AMOUNT} in {ASSET}</p>
            <p className="text-xs break-all px-3 py-3 rounded-[10px]" style={{ backgroundColor: "#F3F4F6", color: NAVY }}>
              {ADDRESS}
            </p>
            <button type="button" onClick={copyAddr} className="w-full h-[48px] rounded-[10px] font-bold text-sm" style={{ border: `1.5px solid ${NAVY}`, color: NAVY }}>
              {copied ? "Copied" : "Copy address"}
            </button>
            
            <div className="pt-2">
              <label className="block text-xs font-bold mb-1" style={{ color: NAVY }}>
                Transaction Hash (TxID)
              </label>
              <input 
                type="text" 
                value={txHash}
                onChange={(e) => setTxHash(e.target.value)}
                placeholder="Paste txid from your wallet"
                className="w-full p-3 border rounded-[10px] text-sm font-mono"
                style={{ borderColor: "#D0D5DD" }}
              />
            </div>

            {error && (
              <p className="text-xs text-red-500 font-semibold" style={{ color: "#EF4444" }}>
                {error}
              </p>
            )}

            <button 
              type="submit" 
              disabled={verifying}
              className="w-full h-[48px] rounded-[10px] font-bold text-sm" 
              style={{ backgroundColor: GOLD, color: NAVY, opacity: verifying ? 0.7 : 1 }}
            >
              {verifying ? "Verifying on Blockchain..." : "I’ve Paid"}
            </button>
          </form>
        </div>

        <div className="flex items-center justify-center gap-6 mt-6">
          <Link to="/choose" className="text-xs" style={{ color: "#9CA3AF" }}>← Back</Link>
        </div>
      </div>
    </div>
  );
}